# Generated by Django 4.2.5 on 2023-09-12 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitoblarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('page', models.SmallIntegerField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='AvtorlarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=50)),
                ('last_name', models.CharField(default=' ', max_length=60)),
                ('date_fo_birth', models.DateTimeField(default=datetime.datetime.now)),
                ('combine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.kitoblarmodel')),
            ],
        ),
    ]
